---
- name: "Fluentd | copy config file"
  become: true
  template:
    src: fluentd-config.yml.j2
    dest: "{{ kube_config_dir }}/fluentd-config.yaml"

- name: "Fluentd | create configMap"
  command: "{{bin_dir}}/kubectl apply -f {{ kube_config_dir }}/fluentd-config.yaml"
  run_once: true

- name: "Fluentd | Write fluentd daemonset"
  become: true
  template:
    src: fluentd-ds.yml.j2
    dest: "{{ kube_config_dir }}/fluentd-ds.yaml"
  register: fluentd_ds_manifest

- name: "Fluentd | Create fluentd daemonset"
  command: "{{ bin_dir }}/kubectl apply -f {{ kube_config_dir }}/fluentd-ds.yaml -n kube-system"
  run_once: true
  when: fluentd_ds_manifest.changed
